-- Seed intangible & natural heritage into Supabase
-- Run in Supabase Dashboard → SQL Editor (after initial_schema.sql)
-- Generated from Front End/gallery-data.js

insert into public.heritage_sites (
  id,
  name,
  category,
  category_label,
  heritage_category,
  ownership,
  location,
  description,
  lat,
  lng,
  cover,
  model_src,
  is_base,
  is_deleted
)
values
  (
    'sambuokan',
    'Sambuokan Festival',
    'intangible',
    'Intangible Cultural Heritage',
    'Festive Events/Festival',
    null,
    'All Barangays, City of Mati',
    'The Sambuokan Festival, celebrated annually in the City of Mati, is a premier cultural event, derived from the Mandaya word "buok", which means "one" or "unity" meaning "to unite as one". Established in 2001 to symbolize the unification of the city''s diverse inhabitants, the festival honors the rich heritage of the Mandaya and Muslim-Kagan tribes alongside other local communities. It is officially recognized as a Significant Cultural Property of the city, serving as a grandiose celebration of resilience, faith, and the harmonious relationship between the people and their environment. The festivities are anchored by the Indak-Indak Dance Competition, a vibrant street-dancing showcase of tribal-inspired choreography, and are further enriched by the Indigenous Peoples Day, agricultural trade fairs, and the official theme song, "Magsambuokan Kita". Observed every October, the festival stands as a testament to Matinians'' commitment to preserving their historical values and cultural identity for future generations.',
    null,
    null,
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2763.jpg',
    null,
    true,
    false
  ),
  (
    'pujada-festival',
    'Pujada Festival',
    'intangible',
    'Intangible Cultural Heritage',
    'Festive Events/Festival',
    null,
    'All Barangays, City of Mati',
    'The Pujada Festival, celebrated annually every June 19th in the City of Mati, Davao Oriental, serves as a vibrant thanksgiving celebration and a vital call for environmental conservation. Formally established to honor the declaration of Pujada Bay as a protected area, the festival highlights the bay''s status as an "ecological jewel" and one of the most biodiverse marine environments in the Philippines. The festivities coincide with the city''s founding anniversary and feature a diverse array of events, including agri-cultural trade fairs, water sports, and the Bangka Race, primarily centered at the Francisco G. Rabat Mati Park and Baywalk. Beyond its aesthetic and socioeconomic contributions, the festival acknowledges the bay as a historical sanctuary and a primary source of livelihood for the community, reinforcing the collective commitment of the government and the people of Mati to preserve its natural majesty for future generations.',
    null,
    null,
    'data/Natural Heritage/Pujada Island/Photographs/pujada island 1.jpg',
    null,
    true,
    false
  ),
  (
    'dioscoro',
    'Works of Dioscoro Vicentino',
    'intangible',
    'Intangible Cultural Heritage',
    'Song Composition',
    null,
    'All Barangays, City of Mati',
    'The Works of Dioscoro B. Vicentino represent a cornerstone of the intangible cultural heritage of the City of Mati and the province of Davao Oriental, serving as a melodic reflection of the region''s identity, values, and natural beauty. This collection of musical compositions includes the official city hymn, "Taga-Mati," which encapsulates the seven core virtues of the local people—being helpful, courteous, respectful, knowledgeable, truthful, obedient, and God-fearing. Other significant works include the Mandaya welcome song "Madayaw na Pag-abot," expressing the innate hospitality of Matinians, and the provincial hymn "Banwa na Madayaw," which celebrates the agricultural richness and spirit of unity. Recognized through local ordinances and resolutions for their profound social and artistic significance, these songs are performed during flag ceremonies and official functions across all 26 barangays to foster a deep sense of pride and belonging within the community.',
    null,
    null,
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/g.png',
    null,
    true,
    false
  ),
  (
    'mamacao',
    'Mamacao Tree',
    'natural',
    'Natural Heritage',
    null,
    null,
    'Purok Mamacaw, Barangay Bobon',
    'The Mamacao Tree (Dracontomelon dao), stands as a living landmark in Purok Mamacaw, Barangay Bobon. Believed to have been planted during the American Colonial Period, the tree features a massive trunk that has grown deep-rooted alongside the community that now bears its name. The site holds deep historical and spiritual significance: during World War II, it served as a place of refuge known as Tagunsaang, while local lore tells of a sacred bird that brought the tree to this spot, where it remains protected by spirits to this day. Though it has faced modern challenges such as infrastructure development and the harvesting of its sturdy roots for agricultural tools, the Mamacaw remains in excellent condition, serving as a resilient symbol of the heritage and natural beauty of the City of Mati.',
    6.865,
    126.3227778,
    'data/Natural Heritage/Mamacao Tree/Photographs/J2048x1536-00472.jpg',
    null,
    true,
    false
  ),
  (
    'taytay-daga',
    'Taytay Daga (Sleeping Dinosaur)',
    'natural',
    'Natural Heritage',
    null,
    null,
    'Sitio Baso, Barangay Badas',
    'The Tay-Tay Daga, popularly known as the Sleeping Dinosaur, is a majestic natural landmark situated in Sitio Baso, Barangay Badas, City of Mati. Spanning approximately 579 hectares, this mountain is famous for its rare and unusual physical formation that naturally resembles a dinosaur resting upon the waters of Pujada Bay. Beyond its aesthetic allure, the site holds profound historical and spiritual significance: it served as a Japanese docking point during World War II, has long been home to indigenous communities, and is steeped in Mandaya language ''Yag Tay-Tay Yang Daga Sang Butay,'' involving guardian spirits and the legendary ''white lady'' of the highlands whom the mountain is named. Formally recognized under Resolution No. 61, Series of 2019, the Sleeping Dinosaur stands as a protected heritage landscape, symbolizing the rich cultural identity and natural grandeur of Mati.',
    6.886209,
    126.184072,
    'data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/Sleeping.jpg',
    null,
    true,
    false
  ),
  (
    'guang-guang',
    'Guang-guang Mangrove Nature Reserve Park',
    'natural',
    'Natural Heritage',
    null,
    null,
    'Barangay Dahican',
    'The Guang-guang Mangrove Nature Reserve Park is a 201-hectare ecological sanctuary in Barangay Dahican. A vital part of the Pujada Bay Protected Landscape, with 19 mangrove species that protects and serves as a natural defense against storm surges and erosion. Visitors can explore via scenic boardwalks and visit the Environmental and Ecotourism Center. As a "cleaner and greener" landmark of Mati, it offers a unique opportunity to witness the rich marine biodiversity and local conservation efforts.',
    6.9154687,
    126.2617709,
    'data/Natural Heritage/Guang-guang Mangrove Nature Reserve Park/Photographs/d.jpg',
    null,
    true,
    false
  ),
  (
    'dahican-shoreline',
    'Dahican Shoreline',
    'natural',
    'Natural Heritage',
    null,
    null,
    'Barangay Dahican',
    'The Dahican Shoreline is a seven-kilometer stretch of white sand and turquoise waters in Dahican. Known as a sanctuary for sea turtles and a hub for professional skimboarding and surfing, this coastal area offers a raw, tropical escape. Experience the natural beauty of the Pacific-facing shores, from watching local surfers master the waves to enjoying the scenic, palm-lined, white sand beach of Mati.',
    6.9243488,
    126.2808986,
    'data/GALLERY/c.jpg',
    null,
    true,
    false
  ),
  (
    'oak-island',
    'Oak Island',
    'natural',
    'Natural Heritage',
    null,
    null,
    'Pujada Bay, Mati City',
    'Oak Island, also known as Vanishing Island, is a stunning white-sand bar in Pujada Bay that emerges only during low tide. Famous for its crystal-clear turquoise waters, it is a premier destination for snorkeling and island hopping in the City of Mati. This protected natural wonder offers a unique, ever-changing landscape that showcases the pristine maritime beauty of Davao Oriental.',
    6.8676,
    126.1913,
    'data/Natural Heritage/Oak Island/Photographs/Oak island1.JPG',
    null,
    true,
    false
  ),
  (
    'pujada-island',
    'Pujada Island',
    'natural',
    'Natural Heritage',
    null,
    null,
    'Pujada Bay, Mati City',
    'Pujada Island is a stunning 157-hectare natural sanctuary and the largest islet in the Pujada Bay. Known for its lush forests, hidden white-sand coves, and vibrant coral reefs, it is a centerpiece of the City of Mati''s environmental heritage. As a protected landscape, it offers visitors a raw encounter with nature, providing a serene escape where the deep blue of the Pacific meets the rich biodiversity of Davao Oriental.',
    6.875278,
    126.183611,
    'data/Natural Heritage/Pujada Island/Photographs/pujada island 1.jpg',
    null,
    true,
    false
  ),
  (
    'pujada-bay',
    'Pujada Bay',
    'natural',
    'Natural Heritage',
    null,
    null,
    'Pujada Bay, Mati City',
    'Pujada Bay is a majestic cove characterized by its turquoise waters, powdery white-sand beaches, and a dramatic backdrop of mountain ranges. It is located downstream of the Mount Hamiguitan Range Wildlife Sanctuary, a UNESCO World Heritage site, and serves as a vital ecological link between the highlands and the ocean (H2O). The bay features a complex network of fertile coral reefs (1,175.75 ha), expansive seagrass beds (610.44 ha), and lush mangrove forests (262.71 ha). The bay''s geography is punctuated by alluring islands and islets, most notably Sleeping Dinosaur, Pujada, Waniban, Oak, and Ivy. It encompasses ten coastal communities—Macambol, Mamali, Dawan, Badas, Central, Matiao, Dahican, Bobon, Tamisan, and Lawigan—where residents interact with nature for both recreation and sustainable livelihoods.',
    6.89139,
    126.22722,
    'data/GALLERY/DJI_0812.jpg',
    null,
    true,
    false
  ),
  (
    'waniban',
    'Waniban Island',
    'natural',
    'Natural Heritage',
    null,
    null,
    'Barangay Tamisan',
    'Waniban Island is a pristine four-hectare islet situated within the protected waters of Pujada Bay and is one of the three primary destinations forming the "Tri-Island" hopping circuit of the City of Mati. Located just a short boat ride from Barangay Tamisan, the island is characterized by a stunning contrast between its powdery white coral sand beaches and a lush, verdant interior. The surrounding marine environment is defined by exceptionally clear turquoise waters, offering high visibility for underwater exploration. The northern side of the island is particularly notable for its vibrant coral gardens and steep underwater drop-offs, establishing it as a premier location for snorkeling and scuba diving. Additionally, the island serves as a natural barrier within the bay, ensuring moderate to calm wave conditions that enhance its appeal as a peaceful recreational sanctuary.',
    6.8324692,
    126.273253,
    'data/GALLERY/Waniban-island.jpg',
    null,
    true,
    false
  )
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  category_label = excluded.category_label,
  heritage_category = excluded.heritage_category,
  ownership = excluded.ownership,
  location = excluded.location,
  description = excluded.description,
  lat = excluded.lat,
  lng = excluded.lng,
  cover = excluded.cover,
  model_src = excluded.model_src,
  is_base = excluded.is_base,
  is_deleted = excluded.is_deleted,
  updated_at = now();

insert into public.heritage_media (
  id,
  site_id,
  type,
  title,
  src,
  caption,
  credit,
  year,
  is_deleted
)
values
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2763.jpg',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A2763',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2763.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2768.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A2768',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2768.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2758.jpg',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A2758',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2758.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2760.jpg',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A2760',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2760.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2784.jpg',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A2784',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2784.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2787.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A2787',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2787.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2806.jpg',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A2806',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2806.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2888.jpg',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A2888',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2888.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2850.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A2850',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2850.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A3031.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A3031',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A3031.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A3170.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A3170',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A3170.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A3597.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A3597',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A3597.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A3652.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A3652',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A3652.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A3813.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A3813',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A3813.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A3865.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A3865',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A3865.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A4090.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A4090',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A4090.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A4202.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A4202',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A4202.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A1025.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A1025',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A1025.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2672.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A2672',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2672.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2714.jpg',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 0M8A2714',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A2714.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/DJI_0160.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — DJI_0160',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/DJI_0160.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/DJI_0172.JPG',
    'sambuokan',
    'photo',
    'Sambuokan Festival — DJI_0172',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/DJI_0172.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/2019-11-25 16-15.jpg',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 2019-11-25 16-15',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/2019-11-25 16-15.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/1.jpg',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 1',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/1.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/2.jpg',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 2',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/2.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/3.jpg',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 3',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/3.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/4.jpg',
    'sambuokan',
    'photo',
    'Sambuokan Festival — 4',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/4.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'sambuokan-link-https://www.facebook.com/share/v/1BJrF8RPCw/',
    'sambuokan',
    'link',
    'Sambuokan 2024 AVP',
    'https://www.facebook.com/share/v/1BJrF8RPCw/',
    null,
    'Mati City LGU',
    '2024',
    false
  ),
  (
    'sambuokan-link-https://www.facebook.com/share/v/187GjP8RnU/',
    'sambuokan',
    'link',
    'Festival Coverage 1',
    'https://www.facebook.com/share/v/187GjP8RnU/',
    null,
    'Mati City LGU',
    '2024',
    false
  ),
  (
    'sambuokan-link-https://www.facebook.com/share/v/17a1o23zw8/',
    'sambuokan',
    'link',
    'Festival Coverage 2',
    'https://www.facebook.com/share/v/17a1o23zw8/',
    null,
    'Sambuokan Festival',
    '2024',
    false
  ),
  (
    'sambuokan-link-https://www.facebook.com/share/v/17d5GepDzw/',
    'sambuokan',
    'link',
    'Festival Coverage 3',
    'https://www.facebook.com/share/v/17d5GepDzw/',
    null,
    'Sambuokan Festival',
    '2024',
    false
  ),
  (
    'sambuokan-link-https://www.facebook.com/share/v/1D6z1aYUnQ/',
    'sambuokan',
    'link',
    'Festival Coverage 4',
    'https://www.facebook.com/share/v/1D6z1aYUnQ/',
    null,
    'Sambuokan Festival',
    '2024',
    false
  ),
  (
    'sambuokan-link-https://www.facebook.com/share/v/1FjcWPBEc1/',
    'sambuokan',
    'link',
    'Festival Coverage 5',
    'https://www.facebook.com/share/v/1FjcWPBEc1/',
    null,
    'Sambuokan Festival',
    '2024',
    false
  ),
  (
    'sambuokan-link-https://www.facebook.com/share/v/1JvzkzeBsh/',
    'sambuokan',
    'link',
    'Festival Coverage 6',
    'https://www.facebook.com/share/v/1JvzkzeBsh/',
    null,
    'Sambuokan Festival',
    '2024',
    false
  ),
  (
    'sambuokan-link-https://www.youtube.com/watch?v=vuxHQafmUz4',
    'sambuokan',
    'link',
    'Official Sambuokan Theme',
    'https://www.youtube.com/watch?v=vuxHQafmUz4',
    null,
    'Mati City LGU',
    null,
    false
  ),
  (
    'sambuokan-link-https://www.youtube.com/watch?v=sGrwCWv-yF0',
    'sambuokan',
    'link',
    'Magsambuokan Kita',
    'https://www.youtube.com/watch?v=sGrwCWv-yF0',
    null,
    'Mati City LGU',
    null,
    false
  ),
  (
    'sambuokan-link-https://www.youtube.com/watch?v=7RV5WJtbzkw',
    'sambuokan',
    'link',
    'Festival Song',
    'https://www.youtube.com/watch?v=7RV5WJtbzkw',
    null,
    'Mati City LGU',
    null,
    false
  ),
  (
    'sambuokan-link-https://www.youtube.com/watch?v=huW2Abc1Ciw',
    'sambuokan',
    'link',
    '2022 Festival Audio',
    'https://www.youtube.com/watch?v=huW2Abc1Ciw',
    null,
    'Mati City LGU',
    '2022',
    false
  ),
  (
    'pujada-festival-photo-data/Natural Heritage/Pujada Island/Photographs/pujada island 1.jpg',
    'pujada-festival',
    'photo',
    'Pujada Festival — pujada island 1',
    'data/Natural Heritage/Pujada Island/Photographs/pujada island 1.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-festival-photo-data/Natural Heritage/Pujada Island/Photographs/pujada island.jpg',
    'pujada-festival',
    'photo',
    'Pujada Festival — pujada island',
    'data/Natural Heritage/Pujada Island/Photographs/pujada island.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-festival-photo-data/Natural Heritage/Pujada Island/Photographs/pujada island-3.jpg',
    'pujada-festival',
    'photo',
    'Pujada Festival — pujada island-3',
    'data/Natural Heritage/Pujada Island/Photographs/pujada island-3.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-festival-photo-data/Natural Heritage/Pujada Island/Photographs/pujada1.jpg',
    'pujada-festival',
    'photo',
    'Pujada Festival — pujada1',
    'data/Natural Heritage/Pujada Island/Photographs/pujada1.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-festival-photo-data/Natural Heritage/Pujada Island/Photographs/PUJADA ISLAND.1.JPG',
    'pujada-festival',
    'photo',
    'Pujada Festival — PUJADA ISLAND.1',
    'data/Natural Heritage/Pujada Island/Photographs/PUJADA ISLAND.1.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-festival-photo-data/Natural Heritage/Pujada Island/Photographs/Pujada Isalnd.JPG',
    'pujada-festival',
    'photo',
    'Pujada Festival — Pujada Isalnd',
    'data/Natural Heritage/Pujada Island/Photographs/Pujada Isalnd.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'dioscoro-photo-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/f.png',
    'dioscoro',
    'photo',
    'Interview of Dioscoro B. Vicentino',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/f.png',
    'Dioscoro B. Vicentino during a recorded interview, reading notes (close view).',
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    '12 July 2025',
    false
  ),
  (
    'dioscoro-photo-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/g.png',
    'dioscoro',
    'photo',
    'Interview of Dioscoro B. Vicentino',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/g.png',
    'Research interview with Dioscoro B. Vicentino, City of Mati.',
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    '12 July 2025',
    false
  ),
  (
    'dioscoro-photo-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/h.png',
    'dioscoro',
    'photo',
    'Interview of Dioscoro B. Vicentino',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/h.png',
    'Documentation of the interview session with Dioscoro B. Vicentino and project team.',
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    '12 July 2025',
    false
  ),
  (
    'dioscoro-photo-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/1.png',
    'dioscoro',
    'photo',
    'I''m A Teacher — composition specimen',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/1.png',
    'A photo of the specimen of Dioscoro B. Vicentino''s composition of "I''m A Teacher".',
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'dioscoro-photo-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/2.png',
    'dioscoro',
    'photo',
    'I''m A Teacher — Teachers'' Magazine',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/2.png',
    'A photo of Teachers'' Magazine where Dioscoro''s composition, "I''m A Teacher" was published dated December, 1995.',
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'dioscoro-photo-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/3.png',
    'dioscoro',
    'photo',
    'I''m A Teacher — national teachers'' song',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/3.png',
    '"I''m A Teacher" was declared by the late Secretary Ricardo T. Gloria as national song for teachers in the Philippines. A photo of the article of Philippine Graphic where Dioscoro''s "I''m A Teacher" was featured July 29, 1996.',
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'dioscoro-photo-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/madayaw na pag-abot.png',
    'dioscoro',
    'photo',
    'Madayaw na Pag-abot — composition specimen',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/madayaw na pag-abot.png',
    'A copy of specimen of Dioscoro B. Vicentino''s composition of "Madayaw na Pag-abot".',
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'dioscoro-photo-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/taga-mati.png',
    'dioscoro',
    'photo',
    'Taga Mati — composition specimen',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/taga-mati.png',
    'A photo of the specimen of Dioscoro B. Vicentino''s composition of "Taga Mati", which was declared as the official anthem of Mati City by virtue of City Ordinance No. 111 series of 2013.',
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'dioscoro-photo-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/banwa na madayaw pg.1.png',
    'dioscoro',
    'photo',
    'Banwa na Madayaw',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/banwa na madayaw pg.1.png',
    'A video with "Banwa na Madayaw" as background music was posted by the City LGU-Mati on their page.',
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'dioscoro-photo-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/banwa na madayaw pg.2.png',
    'dioscoro',
    'photo',
    'Banwa na Madayaw',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/banwa na madayaw pg.2.png',
    'A video with "Banwa na Madayaw" as background music was posted by the City LGU-Mati on their page.',
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'dioscoro-photo-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/mindanao.png',
    'dioscoro',
    'photo',
    'Mindanao — composition specimen',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/mindanao.png',
    'A photo of the specimen of Dioscoro B. Vicentino''s composition of "Mindanao".',
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'dioscoro-photo-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/mindanaocoverpage.png',
    'dioscoro',
    'photo',
    'Mindanao — NCCA choral publication (cover)',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/mindanaocoverpage.png',
    'An image of the composition of choral pieces published by NCCA, which includes one of Dioscoro Bakiao Vicentino''s pieces, "Mindanao" — cover page.',
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'dioscoro-photo-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/4.png.png',
    'dioscoro',
    'photo',
    'Mindanao — NCCA choral publication',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Photographs/4.png.png',
    'Dioscoro Bakiao Vicentino''s piece, "Mindanao" included in the composition of choral pieces published by NCCA.',
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'dioscoro-video-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Videos/Taga Mati.mp4',
    'dioscoro',
    'video',
    'Taga Mati',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Videos/Taga Mati.mp4',
    'Official video of "Taga Mati," the official anthem of Mati City by virtue of City Ordinance No. 111 series of 2013.',
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'dioscoro-video-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Videos/Banwa na Madayaw.mp4',
    'dioscoro',
    'video',
    'Banwa na Madayaw',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Videos/Banwa na Madayaw.mp4',
    'Provincial hymn "Banwa na Madayaw," composed by Dioscoro B. Vicentino.',
    'Cris Vincent Olvida. https://www.youtube.com/watch?v=Ta52YMq9bhs',
    null,
    false
  ),
  (
    'dioscoro-video-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Videos/I''m A Teacher.mp4',
    'dioscoro',
    'video',
    'I''m A Teacher',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Videos/I''m A Teacher.mp4',
    '"I''m A Teacher" — performed by SDO Digos City Harmonic Mentors.',
    'Rodolfo II Osorno. https://www.youtube.com/watch?v=I1U3gsrqT7I',
    null,
    false
  ),
  (
    'dioscoro-audio-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Audio Recordings/Taga Mati.mp3',
    'dioscoro',
    'audio',
    'Taga Mati',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Audio Recordings/Taga Mati.mp3',
    null,
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'dioscoro-audio-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Audio Recordings/Banwa na Madayaw.mp3',
    'dioscoro',
    'audio',
    'Banwa na Madayaw',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Audio Recordings/Banwa na Madayaw.mp3',
    null,
    'Cris Vincent Olvida. https://www.youtube.com/watch?v=Ta52YMq9bhs',
    null,
    false
  ),
  (
    'dioscoro-audio-data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Audio Recordings/I''m a Teacher.mp3',
    'dioscoro',
    'audio',
    'I''m a Teacher',
    'data/Intangible Cultural Heritage/Works of Dioscoro Vicentino/Audio Recordings/I''m a Teacher.mp3',
    null,
    'Rodolfo II Osorno. https://www.youtube.com/watch?v=I1U3gsrqT7I',
    null,
    false
  ),
  (
    'mamacao-photo-data/Natural Heritage/Mamacao Tree/Photographs/J2048x1536-00472.jpg',
    'mamacao',
    'photo',
    'Mamacao Tree',
    'data/Natural Heritage/Mamacao Tree/Photographs/J2048x1536-00472.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'taytay-daga-photo-data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/Sleeping.jpg',
    'taytay-daga',
    'photo',
    'Taytay Daga — Sleeping',
    'data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/Sleeping.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'taytay-daga-photo-data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/DJI_0754.jpg',
    'taytay-daga',
    'photo',
    'Taytay Daga — DJI_0754',
    'data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/DJI_0754.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'taytay-daga-photo-data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/DJI_0761.jpg',
    'taytay-daga',
    'photo',
    'Taytay Daga — DJI_0761',
    'data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/DJI_0761.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'taytay-daga-photo-data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/DJI_0771.jpg',
    'taytay-daga',
    'photo',
    'Taytay Daga — DJI_0771',
    'data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/DJI_0771.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'taytay-daga-photo-data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/DJI_0786.jpg',
    'taytay-daga',
    'photo',
    'Taytay Daga — DJI_0786',
    'data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/DJI_0786.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'taytay-daga-photo-data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/DJI_0801.jpg',
    'taytay-daga',
    'photo',
    'Taytay Daga — DJI_0801',
    'data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/DJI_0801.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'taytay-daga-photo-data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/DJI_0812.jpg',
    'taytay-daga',
    'photo',
    'Taytay Daga — DJI_0812',
    'data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/DJI_0812.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'taytay-daga-photo-data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/2020-01-14 10-24.jpg',
    'taytay-daga',
    'photo',
    'Taytay Daga — 2020-01-14 10-24',
    'data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/2020-01-14 10-24.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'taytay-daga-photo-data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/J1926x1109-00300.jpg',
    'taytay-daga',
    'photo',
    'Taytay Daga — J1926x1109-00300',
    'data/Natural Heritage/Taytay Daga (Sleeping Dinosaur)/Photographs/J1926x1109-00300.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'guang-guang-photo-data/Natural Heritage/Guang-guang Mangrove Nature Reserve Park/Photographs/d.jpg',
    'guang-guang',
    'photo',
    'Guang-guang Mangrove Nature Reserve Park',
    'data/Natural Heritage/Guang-guang Mangrove Nature Reserve Park/Photographs/d.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'dahican-shoreline-photo-data/GALLERY/c.jpg',
    'dahican-shoreline',
    'photo',
    'Dahican Shoreline',
    'data/GALLERY/c.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'dahican-shoreline-photo-data/GALLERY/z.jpg',
    'dahican-shoreline',
    'photo',
    'Dahican Coast',
    'data/GALLERY/z.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'dahican-shoreline-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A3597.JPG',
    'dahican-shoreline',
    'photo',
    'Skimboarding at Dahican',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/0M8A3597.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'dahican-shoreline-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/DJI_0172.JPG',
    'dahican-shoreline',
    'photo',
    'Dahican from above',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/DJI_0172.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'oak-island-photo-data/Natural Heritage/Oak Island/Photographs/Oak island1.JPG',
    'oak-island',
    'photo',
    'Oak Island — Oak island1',
    'data/Natural Heritage/Oak Island/Photographs/Oak island1.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'oak-island-photo-data/Natural Heritage/Oak Island/Photographs/Oak island.JPG',
    'oak-island',
    'photo',
    'Oak Island — Oak island',
    'data/Natural Heritage/Oak Island/Photographs/Oak island.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'oak-island-photo-data/Natural Heritage/Oak Island/Photographs/Oak-Island.jpg',
    'oak-island',
    'photo',
    'Oak Island — Oak-Island',
    'data/Natural Heritage/Oak Island/Photographs/Oak-Island.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'oak-island-photo-data/Natural Heritage/Oak Island/Photographs/Oak & Pujada island.JPG',
    'oak-island',
    'photo',
    'Oak Island — Oak & Pujada island',
    'data/Natural Heritage/Oak Island/Photographs/Oak & Pujada island.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'oak-island-video-data/Natural Heritage/Oak Island/Videos/OAK ISLAND.mp4',
    'oak-island',
    'video',
    'Oak Island Video 1',
    'data/Natural Heritage/Oak Island/Videos/OAK ISLAND.mp4',
    null,
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'oak-island-video-data/Natural Heritage/Oak Island/Videos/OAK ISLAND.1.mp4',
    'oak-island',
    'video',
    'Oak Island Video 2',
    'data/Natural Heritage/Oak Island/Videos/OAK ISLAND.1.mp4',
    null,
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'oak-island-video-data/Natural Heritage/Oak Island/Videos/OAK ISLAND.2.mp4',
    'oak-island',
    'video',
    'Oak Island Video 3',
    'data/Natural Heritage/Oak Island/Videos/OAK ISLAND.2.mp4',
    null,
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'oak-island-video-data/Natural Heritage/Oak Island/Videos/OAK ISLAND.3.mp4',
    'oak-island',
    'video',
    'Oak Island Video 4',
    'data/Natural Heritage/Oak Island/Videos/OAK ISLAND.3.mp4',
    null,
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'oak-island-video-data/Natural Heritage/Oak Island/Videos/OAK ISLAND.4.mp4',
    'oak-island',
    'video',
    'Oak Island Video 5',
    'data/Natural Heritage/Oak Island/Videos/OAK ISLAND.4.mp4',
    null,
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'pujada-island-photo-data/Natural Heritage/Pujada Island/Photographs/pujada island 1.jpg',
    'pujada-island',
    'photo',
    'Pujada Island — pujada island 1',
    'data/Natural Heritage/Pujada Island/Photographs/pujada island 1.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-island-photo-data/Natural Heritage/Pujada Island/Photographs/pujada island.jpg',
    'pujada-island',
    'photo',
    'Pujada Island — pujada island',
    'data/Natural Heritage/Pujada Island/Photographs/pujada island.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-island-photo-data/Natural Heritage/Pujada Island/Photographs/pujada island-3.jpg',
    'pujada-island',
    'photo',
    'Pujada Island — pujada island-3',
    'data/Natural Heritage/Pujada Island/Photographs/pujada island-3.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-island-photo-data/Natural Heritage/Pujada Island/Photographs/pujada1.jpg',
    'pujada-island',
    'photo',
    'Pujada Island — pujada1',
    'data/Natural Heritage/Pujada Island/Photographs/pujada1.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-island-photo-data/Natural Heritage/Pujada Island/Photographs/PUJADA ISLAND.1.JPG',
    'pujada-island',
    'photo',
    'Pujada Island — PUJADA ISLAND.1',
    'data/Natural Heritage/Pujada Island/Photographs/PUJADA ISLAND.1.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-island-photo-data/Natural Heritage/Pujada Island/Photographs/Pujada Isalnd.JPG',
    'pujada-island',
    'photo',
    'Pujada Island — Pujada Isalnd',
    'data/Natural Heritage/Pujada Island/Photographs/Pujada Isalnd.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-island-video-data/Natural Heritage/Pujada Island/Videos/1.mp4',
    'pujada-island',
    'video',
    'Pujada Island Video 1',
    'data/Natural Heritage/Pujada Island/Videos/1.mp4',
    null,
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'pujada-island-video-data/Natural Heritage/Pujada Island/Videos/2.mp4',
    'pujada-island',
    'video',
    'Pujada Island Video 2',
    'data/Natural Heritage/Pujada Island/Videos/2.mp4',
    null,
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'pujada-island-video-data/Natural Heritage/Pujada Island/Videos/3.mp4',
    'pujada-island',
    'video',
    'Pujada Island Video 3',
    'data/Natural Heritage/Pujada Island/Videos/3.mp4',
    null,
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'pujada-island-video-data/Natural Heritage/Pujada Island/Videos/4.mp4',
    'pujada-island',
    'video',
    'Pujada Island Video 4',
    'data/Natural Heritage/Pujada Island/Videos/4.mp4',
    null,
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'pujada-island-video-data/Natural Heritage/Pujada Island/Videos/5.mp4',
    'pujada-island',
    'video',
    'Pujada Island Video 5',
    'data/Natural Heritage/Pujada Island/Videos/5.mp4',
    null,
    'City Tourism and Promotions Office, City of Mati, Davao Oriental, Philippines',
    null,
    false
  ),
  (
    'pujada-bay-photo-data/GALLERY/DJI_0812.jpg',
    'pujada-bay',
    'photo',
    'Pujada Bay aerial view',
    'data/GALLERY/DJI_0812.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-bay-photo-data/GALLERY/pujada island 1.jpg',
    'pujada-bay',
    'photo',
    'Pujada Bay waters',
    'data/GALLERY/pujada island 1.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-bay-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/DJI_0172.JPG',
    'pujada-bay',
    'photo',
    'Pujada Bay coastline',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/DJI_0172.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-bay-photo-data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/DJI_0160.JPG',
    'pujada-bay',
    'photo',
    'Mati and Pujada Bay',
    'data/Intangible Cultural Heritage/Sambuokan Festival/Photographs/DJI_0160.JPG',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-bay-photo-data/Natural Heritage/Pujada Island/Photographs/pujada island.jpg',
    'pujada-bay',
    'photo',
    'Pujada Bay seascape',
    'data/Natural Heritage/Pujada Island/Photographs/pujada island.jpg',
    null,
    null,
    null,
    false
  ),
  (
    'pujada-bay-link-https://www.youtube.com/watch?v=Xn_enezYdNM',
    'pujada-bay',
    'link',
    'Bay Celebration',
    'https://www.youtube.com/watch?v=Xn_enezYdNM',
    null,
    'Mati City LGU',
    null,
    false
  ),
  (
    'waniban-photo-data/GALLERY/Waniban-island.jpg',
    'waniban',
    'photo',
    'Waniban Island',
    'data/GALLERY/Waniban-island.jpg',
    null,
    null,
    null,
    false
  )
on conflict (id) do update set
  site_id = excluded.site_id,
  type = excluded.type,
  title = excluded.title,
  src = excluded.src,
  caption = excluded.caption,
  credit = excluded.credit,
  year = excluded.year,
  is_deleted = excluded.is_deleted;
